title:            Bas Tichelaar
description:      Blog of an entreprenerd
disqus_shortname: bastichelaar
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:

# Owner/author information
owner:
  name:           Bas Tichelaar
  avatar:         bastichelaar.jpg
  bio:            "Consultant at Xebia and Co Founder of Cargonauts"
  email:          bas@tichelaar.io
  # Social networking links used in footer. Update and remove as you like.
  twitter:        bastichelaar
  facebook:       
  github:         bastichelaar 
  stackexchange:  
  linkedin:       bastichelaar
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  #google_plus:    +bastichelaar

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:  UA-60213162-1 
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Amsterdam
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]